### PR TITLE
Working solvers time dependent#292

### PR DESCRIPTION
**Pull request by pietercollins**

### CODE REVIEW

**Comment by lgeretti** [comment]
Using gcc there are a few trivial sign conversion warnings, along with the potential errors of #295.

**Comment by pietercollins** [comment]
We can fix the sign warnings later; some of them may be in the working branch already.
I've updated the Python tutorial.
Is there a way of running the Python tutorial with the tests? It's nice to check everything before doing the continuous integration (saves time).

**Comment by lgeretti** [comment]
The working branch currently only has the warnings from #295 pending. Indeed I am still a bit undecided if we should just set "-Werror" altogether also for the working branch. I don't see a particular motivation for leaving warnings behind when we can fix them as soon as they crop up.

Regarding the Python tutorial, it is not in the pytest format hence we would not be able to capture the error produced by it automatically. We could just duplicate it and wrap it in that format, making it also a test. But I would rather prefer to keep concerns separated and enrich the test suite to cover everything that the tutorial shows.

**Comment by pietercollins** [comment]
I would prefer to automatically test everything that the continuous integration requires. We could add a "test_tutorial.py" file which runs the tutorial.

**Comment by lgeretti** [comment]
This can be done for the Python tutorial(s). For the C++ tutorials it would slow down the suite and require some refactoring of the tutorials code itself to support its encapsulation.

**Comment by pietercollins** [comment]
I agree, just for the Python tutorial.
For the other tutorials, we can check they compile.

**Pull request merged**
