### PR TITLE
Implemented Bounder and related tests

### PR DESCRIPTION
**Pull request by lgeretti**
I implemented the Bounder functionality (no enum class defined) along with some basic tests.

For now the Bounder class is used as the implementation of flow_bounds in both the Integrator and DifferentialInclusionIntegrator, so we have a unique implementation.

As for the routine that calculates the bounds, I used IntegratorBase::flow_bounds as reference. While the "simplified" one from DifferentialInclusionIntegrator worked well on the DI examples, it wasn't robust enough for test_hybrid_reachability_analyser: using it made the test require ~13 times the execution time as usual, i.e., the step size chosen was smaller than necessary.

### CODE REVIEW

**Comment by lgeretti** [comment]
Before choosing to give a set_bounder method to the Integrator, shouldn't we decide if we want to actually decouple Integrator and Bounder?

**Comment by pietercollins** [comment]
I'll think about this. We *could* have a FlowStepper class to fully orthogonalise the bounds and step. 
For now, it's safe to add set_bounder to the class which has a Bounder variable.

**Comment by lgeretti** [comment]
Ok, summarizing:

1. Why do you say they are not sound? However, I'll remove the bounder classes apart from Euler, since I am unable to prove the soundness. Could you work on that though?

2. I'll add a minimum of documentation. Here `formula` just provides the formula excluding the initial set box (which can be enlarged or not, depending on being working on the initial bound or its refinement), and it is implemented by the specific bounder. The `_initial` and `_refinement` methods use `formula` and are implemented in `BounderBase`, hence they are private.

3. I'll extend the information, though my original intent was to give a "short-name" description to the Bounder method only. For a very complex configuration it can be worth having short names that provide only the minimal info. Don't know how to best support both full-name and short-name cases though.

4. I'll fix the Handle according to the coding guideline you mentioned. And yes, it would be nice if you could write a coding guidelines document (for me, but for any prospective contributor in the future).

5. I'll make constants for what's worth configuring.

6. The bounder works in the presence of a generic R^{n+m} -> R^{n} function, do we really need to discriminate between VectorField and DifferentialInclusion? Particularly if the DifferentialInclusion class is unable to use the functional representation and needs the symbolic representation.

7. How shall I better clean up the bounders from the destructor? I just followed the Integrator approach you used and avoided any warnings the compiler would have issued.

7. I'll add the set_bounder method then, for now.

**Comment by pietercollins** [comment]
1. I'm pretty sure they're not sound as these methods are not rigorous, so I won't work on it further.
6. At some point we'll want to distinguish differential inclusions and parameterised systems, so it will be good to keep states and parameters separate. It's not critical we do this right now though, so you could keep your implementation. Still, the behaviour should be documented.
7. If the destructor of a derived class does not do any work other than call the base destructor, you don't have to implement it (including `= default`).

**Comment by lgeretti** [comment]
1. Why did you suggest in the first place to use higher-order methods for bounding, if you consider them not rigorous? Do you know of any higher-order method that may be fit for implementation?
2. I am not sure that distinguishing would be clean unless we use expressions, but we will see when and if we get there

**Comment by lgeretti** [comment]
4. Shall I implement the Handle by subclassing from Handle<BounderInterface>, or is there a reason why some classes don't do that?

**Comment by lgeretti** [comment]
I fixed the pending issues.

Since we have just one Bounder implementation, the changes do not assume anything about the behavior of a bounder and BounderBase is empty For the same reason, it would have made little sense to introduce a BounderConfiguration and the constants are still kept hard-written within the Euler bounder. 

So in the end I did the following changes:

  1. Remove all bounders except for EulerBounder
  2. Refactor all the implementation in the EulerBounder
  3. Implement the BounderHandle properly
  4. Add const& specification to all inputs
  5. Add a bounder() and set_bounder() methods to IntegratorBase, defaulting to EulerBounder, then flow_bounds in an Integrator calls the BounderInterface::compute method from the internal bounder.
  6. Add the minimum required documentation to BounderInterface

**Pull request merged**
