### PR TITLE
Tutorials#477

### PR DESCRIPTION
**Pull request by pietercollins**
I've changed the Python rigorous_numerics_tutorial to modules_tutorial. I'm not sure if this is the best name for it. Originally, its purpose was mostly to highlight Python-esque ways of doing things. It mostly just lists the main operations and their syntax in the core modules. 

I translated the C++ rigorous_numerics_tutorial to Python, and the modules_tutorial to C++.

I think its reasonably worth  keeping both kinds of tutorial, though maybe the modules_tutorial should be renamed to something other that "tutorial". I've called the internal function "xxx_demonstration". At some point, we may wish to review the operations which we demonstrate.

Currently, there's a Doxygen page for the C++ rigorous_numerics_tutorial and the Python modules_tutorial. They're using quite different styles, the former using `\snippet` and the latter `\skipline`. The former is _much_ easier to maintain! Let me know if you prefer one of the styles.

### CODE REVIEW

**Comment by lgeretti** [comment]
I don't understand the separation between modules and rigorous_numerics. For example, what does one in the linear algebra demonstration that the other does not already?

My suggestions is either to merge the two, or to separate across modules.

In any case the name modules, unless it actually covers all modules, should be given another name in my opinion. Kernel would be better in this respect.

As for the dox, use the syntax that is easier to maintain for you.

**Review by lgeretti — CHANGES_REQUESTED** [review]
I don't understand the separation between modules and rigorous_numerics. For example, what does one in the linear algebra demonstration that the other does not do already?

My suggestions is either to merge the two, or to separate across modules.

In any case the name modules, unless it actually covers all modules, should be given another name in my opinion. Kernel would be better in this respect.

As for the dox, use the syntax that is easier to maintain for you.

As a final operation, let's not forget that .github/workflows/ci.yml must be updated to include two extra steps for the new cpp/python tutorial.

**Comment by pietercollins** [comment]
I thought about splitting the "modules" tutorial across the modules, but since the `CMakefiles.txt` in `tutorials/` assumes a single target per directory with a specific naming, I wasn't quite sure how to restructure it.
The `rigorous_numerics_tutorial` is the real tutorial. The `modules_tutorial` is more (but not exclusively) to show the available methods and the syntax (and syntax differences).I think the latter is worth keeping, but maybe not under the label `tutorial`.

**Comment by lgeretti** [comment]
I don't know where the modules one could go, other than tutorial.

By the way, we should make all python scripts executable on the python3 interpreter explicitly. Using python may call python 2 on some machines, and it is not supported anymore.

**Comment by pietercollins** [comment]
I've split the `modules_tutorial` into separate files for each module, `numeric_demonstrations` etc,, and also added an (empty) `geometry_demonstration`.

If you think the setup is ok, I'll add some material for Geometry, and maybe expand some of the other modules a little (let me know if there's anything specific I should add) and hopefully this will be sufficient.

**Comment by pietercollins** [comment]
Branch should be ready for merging.

**Review by lgeretti — APPROVED** [review]

**Pull request merged**
